name: Web CI

on:
  push:
    branches: [ main ]
    paths:
      - "webapp/gemensam-eko-web/**"
      - ".github/workflows/web-ci.yml"
  pull_request:
    branches: [ main ]

jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp/gemensam-eko-web
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: webapp/gemensam-eko-web/package.json

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build (smoke test)
        run: npm run build
